name: Release Extension

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release Extension"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: pnpm
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Create GitHub Release (if missing)
        run: |
          gh release create "$GITHUB_REF_NAME" \
            --title "$GITHUB_REF_NAME" \
            --notes "Release for $GITHUB_REF_NAME" \
            --draft=false \
            --prerelease=false
        env:
          GH_TOKEN: ${{ github.token }}
      
      - name: Build and Zip Extension
        run: |
          pnpm zip
          pnpm zip:firefox
        # env:
        #   WXT_GOOGLE_CLIENT_ID: ${{ secrets.WXT_GOOGLE_CLIENT_ID }}

      - name: Upload Extension Zip to Release
        run: gh release upload "$GITHUB_REF_NAME" .output/*-*.zip --clobber
        env:
          GH_TOKEN: ${{ github.token }}
